tx=input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(tx)}')
print(f'Só tem espaços? {tx.isspace()}')
print(f'É um número? {tx.isnumeric()}')
print(f'É alfabético? {tx.isalpha()}')
print(f'É alfanumérico? {tx.isalnum()}')
print(f'Está em maiúsculas? {tx.isupper()}')
print(f'Está em minúsculas? {tx.islower()}')
print(f'Está capitalizada? {tx.istitle()}')